---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes
configure_dock: yes

dotfiles_repo: https://github.com/05tb/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Documents/git-repos/dotfiles
dotfiles_files:
  - .gitignore
  - .osx
  - .zshrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - pyenv 
  - pyenv-virtualenv
  - git 
  - terraform
  - dockutil
  - mas
  - zlib
  - readline
  - xz
  - zsh 
  - zsh-completions

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - bartender
  - bbc-iplayer-downloads
  - docker
  - dropbox
  # - firefox
  - iterm2
  - itsycal
  - jupyter-notebook-viewer
  - nightowl
  - oversight # causing some issues?
  - postman
  - pycharm-ce
  - qfinder-pro
  - rescuetime
  - screens-connect
  - skype-for-business
  - slack
  - superduper
  - texmaker
  - ultimaker-cura
  - vagrant 
  - virtualbox
  - virtualbox-extension-pack
  - visual-studio-code
  - vlc
  - webex-teams
  - whatsapp
  - zenmap
  - zoom.us
  - zotero

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: 
  # - { id: 497799835, name: "Xcode" }
  - { id: 937984704, name: "Amphetamine" }
  - { id: 1091189122, name: "Bear" }
  - { id: 1160374471, name: "PiPifier" }
  - { id: 1436953057, name: "GhosteryLite" }
  - { id: 425424353, name: "The Unarchiver" }
  - { id: 409201541, name: "Pages" }
  - { id: 409183694, name: "Keynote" }
  - { id: 409203825, name: "Numbers" }
  - {id: 1287445660, name: "Agenda"}
  - {id: 568494494, name: "Pocket"}
  - {id: 1477385213, name: "Save to Pocket"}
  - {id: 1440147259, name: "AdGuard for Safari"}
# mas_email: ""
# mas_password: ""
# mas_signin_dialog: yes

# vscode_extensions_to_install:
users:
  - username: toddb
    visual_studio_code_extensions:
      - ms-python.python
      - streetsidesoftware.code-spell-checker
      - shd101wyy.markdown-preview-enhanced
      - peterjausovec.vscode-docker
      - mauve.terraform
      - jithurjacob.nbpreviewer
      - eamodio.toggle-excluded-files
      - eamodio.gitlens
      - devine-davies.make-hidden
      - dbaeumer.vscode-eslint
      - gruntfuggly.todo-tree

dockitems_to_remove:
  - Launchpad
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - News
  - iTunes
  - iBooks
  - App Store
  - Siri
  - Skype for Business

dockitems_to_persist:
  - name: Mail
    path: "/Applications/Mail.app"
    pos: 1
  - name: Slack
    path: "/Applications/Slack.app"
    pos: 2
  - name: Agenda
    path: "/Applications/Agenda.app"
    pos: 3
  - name: Calendar
    path: /Applications/Calendar.app
    pos: 4
  - name: Safari
    path: /Applications/Safari.app
    pos: 5
  - name: iTunes
    path: /Applications/iTunes.app
    pos: 6
  - name: Visual Studio Code
    path: /Applications/Visual Studio Code.app
    pos: 7
  - name: iTerm
    path: /Applications/Utilities/iTerm.app
    pos: 8
  - name: System Preferences
    path: /Applications/System Preferences.app
    pos: 9

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
