---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes
configure_dock: yes

dotfiles_repo: https://github.com/05tb/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Documents/git-repos/dotfiles
dotfiles_files:
  - .gitignore
  - .osx

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - pyenv 
  - pyenv-virtualenv
  - git 
  - bash-completion
  - terraform
  - dockutil
  - mas

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password6
  - bartender
  - bbc-iplayer-downloads
  - docker
  - dropbox
  - firefox
  - itsycal
  - oversight # causing some issues?
  - postman
  - pycharm-ce
  - screens-connect
  - skype-for-business
  - slack
  - superduper
  - texmaker
  - visual-studio-code
  - vlc
  - webex-teams
  - whatsapp
  - nightowl
  - zenmap
  - zotero
  - virtualbox
  - virtualbox-extension-pack
  - vagrant 

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: 
  - { id: 497799835, name: "Xcode" }
  - { id: 1432731683, name: "Adblock Plus" }
  - { id: 1335413823, name: "Ka-Block!" }
  - { id: 937984704, name: "Amphetamine" }
  - { id: 1091189122, name: "Bear" }
  - { id: 1160374471, name: "PiPifier" }
  - { id: 1436953057, name: "GhosteryLite" }
  - { id: 425424353, name: "The Unarchiver" }
  - { id: 409201541, name: "Pages" }
  - { id: 409183694, name: "Keynote" }
  - { id: 409203825, name: "Numbers" }
# mas_email: ""
# mas_password: ""
# mas_signin_dialog: yes

dockitems_to_remove:
  - Launchpad
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - News
  - iTunes
  - iBooks
  - App Store
  - Siri

dockitems_to_persist:
  - name: Mail
    path: "/Applications/Mail.app"
    pos: 1
  - name: Slack
    path: "/Applications/Slack.app"
    pos: 2
  - name: Calendar
    path: /Applications/Calendar.app
    pos: 3
  - name: Safari
    path: /Applications/Safari.app
    pos: 4
  - name: Visual Studio Code
    path: /Applications/Visual Studio Code.app
    pos: 5
  - name: Terminal
    path: /Applications/Utilities/Terminal.app
    pos: 6
  - name: System Preferences
    path: /Applications/System Preferences.app
    pos: 7

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
