---
- hosts: all
  connection: local

  # `mas signin` command disabled on macOS >10.13, use pause and manual sign in instead
  # vars_prompt:
  # - name: "mas_email"
  #   prompt: "Enter Apple App Store Account Email"
  #   private: no

  # - name: "mas_password"
  #   prompt: "Enter Apple App Store Account Password"
  #   private: yes

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']
    - name: Mac App Store Sign in
      pause:  
        prompt: "Please sign into the Mac App Store - Press Enter when done"

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ['mas']
    # - role: gantsign.visual-studio-code-extensions
    #   tags: ['vscode']

  tasks:
    - include_tasks: tasks/ansible-setup.yml

    - include_tasks: tasks/sudoers.yml
      when: configure_sudoers

    # - include_tasks: tasks/oh-my-zsh.yml
    #   when: configure_oh_my_zsh

    - include_tasks: tasks/terminal.yml
      when: configure_terminal

    - include_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - include_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - include_tasks: tasks/dock-setup.yml
      when: configure_dock
      tags: ['dock']

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
